# Generated by Django 5.2.1 on 2025-05-21 00:07
from django.contrib.postgres.operations import TrigramExtension 
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [

        TrigramExtension() 
    ]
